### ISSUE TITLE
Is Edge instead of Internet Explorer possible?

### ISSUE THREAD

**Issue by ghaspias** [javalikescript/lua-webview#2]
Hi,

the github page for WebView states it uses Edge on Windows platform. However, lua-webview, on Windows 10, gives me... Internet Explorer 11.
Is that your choice, or is there some issue preventing the use of the more modern and capable Edge? Or is it the result of some misconfiguration on my part?
I tested WebViewJar, a Java wrapper for WebView, and although it launches an Edge view, communication with the WebView is broken...

**Comment by javalikescript** [comment]
Hi,
Thank you for submitting the issue, you make me realize that the [webview](https://github.com/zserge/webview) library has been updated in March 2020.
I did not moved the Lua module to the latest version and so it is still based on IE 11 as you saw.
Samuel

**Comment by ghaspias** [comment]
Cool, thanks for the updates! Is there some magic dust required to get it to use Edge? I still get IE 11.

**Comment by javalikescript** [comment]
Hi,
The Edge support is still a work in progress, the original webview library has too much changes to be used. MSHTML, IE 11, is used as fallback.
The new version of Edge, Chromium-based, is required as well as the `WebView2Loader.dll` library from the Microsoft Edge WebView2 SDK. This library must be located in the Lua executable directory or in a directory referenced by the environment variable `WEBVIEW2_WIN32_PATH`.
I assume that Edge, the SDK library, the lua-webview library and Lua shall have the same architecture 32 or 64 bits.
I tested it on Windows 10 64 bits version 1909 and Edge version 81.0.416.68.
If it still not works despite this prerequisites I am very interested to find the bug and fix it.
Samuel

**Comment by javalikescript** [comment]
Hi,
I had the opportunity to come across a web view using IE despite Edge been installed.
It seems that the WebView2 SDK detection of Edge installation is not working properly.
In this case, it is possible to indicate the correct installation path by using the environment variable `WEBVIEW2_BROWSER_EXECUTABLE_FOLDER` prior launching lua-webview.
Such as:
`set WEBVIEW2_BROWSER_EXECUTABLE_FOLDER=C:\Program Files (x86)\Microsoft\Edge\Application\83.0.478.54`
Hope it helps,
Samuel

**Comment by ghaspias** [comment]
Hi, thanks for your suggestions. I have since tried a few times, never got it to work. I now have Edge 80.0.522.63, and luajls-5.4-x86_64-w64-mingw32.20200819.zip, and still uses IE11. Experimented with setting WEBVIEW2_BROWSER_EXECUTABLE_FOLDER and/or WEBVIEW2_WIN32_PATH, with the same result. I have also tried [DeskGap](https://github.com/patr0nus/DeskGap), which loads Edge 44!
I will try on a different machine, and I'll report the results.

**Comment by javalikescript** [comment]
Hi,
If you try again, you could launch [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) in order to get raw debug output from webview such as:
```
Loading WebView2Loader (0.9.430)
found potential WebView2 executable folder, use WEBVIEW2_DISABLE_AUTO_DETECT to disable
C:\Program Files (x86)\Microsoft\Edge\Application\84.0.522.59
WebView2Loader.dll
WebView2 enabled
84.0.522.59
RecursiveDirectoryCreate( C:\Users\samue\AppData\Roaming\\lua.exe.WebView2\EBWebView directory exists )
```
Have a good day,
Samuel

**Comment by javalikescript** [comment]
Closing this issue as Edge (Chromium) has reached GA and requires the WebView2 Runtime, see https://github.com/javalikescript/webview-c#edge
