### ISSUE TITLE
arch linux luarocks install, test run error

### ISSUE THREAD

**Issue by futurepaycc** [javalikescript/lua-webview#3]
test.lua:
`require('webview').open('https://m.baidu.com/')`

lua: error loading module 'webview' from file '/usr/lib/lua/5.3/webview.so':
	/usr/lib/lua/5.3/webview.so: undefined symbol: webkit_web_view_get_type

luastatic ok:
luastatic tes.lua -llua5.3 -I /usr/include/lua5.3 `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0`

lua newbie, 
link config problem?

**Comment by javalikescript** [comment]
Hello,

Thank you for trying lua-webview and taking the time to report this issue.
I am not an expert in luarocks nor in Linux.
I installed ArchLinux and GNOME in a VirtualBox VM and managed to get a running webview.

You could try the latest all in one luajls package containing both Lua, here 5.4, and lua-webview:
```sh
wget http://javalikescript.free.fr/lua/download/luajls-5.4-x86_64-linux-gnu.20200811.tar.gz
gunzip luajls-5.4-x86_64-linux-gnu.20200811.tar.gz
mkdir luajls-5.4
cd luajls-5.4
tar xvf ../luajls-5.4-x86_64-linux-gnu.20200811.tar
./lua -e "require('webview').open('https://m.baidu.com/')"
```

You could try webview without Lua:
```sh
git clone https://github.com/javalikescript/webview-c.git
cd webview-c
gcc webview-example.c -DWEBVIEW_GTK=1 `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0` -o webview-example
./webview-example
```

You could inspect the output of the luarocks install command, more specifically the compilation part, in my case:
```sh
gcc -O2 -fPIC -pedantic -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -Iwebview-c -I/usr/include/lua5.3 -DWEBVIEW_GTK=1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/webkitgtk-4.0 -I/usr/include/libsoup-2.4 -pthread -I/usr/include/libxml2  -c -o webview.o webview.c
webview.c:145:2: warning: ISO C does not allow extra ‘;’ outside of a function [-Wpedantic]
  145 | };
      |  ^
webview.c:152:2: warning: ISO C does not allow extra ‘;’ outside of a function [-Wpedantic]
  152 | };
      |  ^
gcc webview.o -shared -static-libgcc -Wl,-s -L/home/samuel/lua-5.3.5_Linux415_64_lib/ -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -ljavascriptcoregtk-4.0 -lgobject-2.0 -lglib-2.0  -o webview.so
cp webview.so /home/samuel/.luarocks/lib/luarocks/rocks-5.3/lua-webview/1.2-1/lib

lua-webview 1.2-1 is now installed in /home/samuel/.luarocks (license: MIT)
```

Let me know if it helps and have a great day,
Samuel

**Comment by futurepaycc** [comment]
thx  for reply, I'll try  build webview-c and link to lua or use luajit ffi

but still hope u can check the luarocks package link problem

**Comment by javalikescript** [comment]
Hello,

I was not able to reproduce the luarocks package link problem.
I used luarocks on ArchLinux with GNOME to install lua-webview and I managed to open the webview window, as follow.
```sh
pacman -S luarocks lua53 git make gcc
wget https://downloads.sourceforge.net/project/luabinaries/5.3.5/Linux%20Libraries/lua-5.3.5_Linux44_64_lib.tar.gz
gunzip lua-5.3.5_Linux44_64_lib.tar.gz
mkdir lua-5.3.5_Linux44_64_lib
cd lua-5.3.5_Linux44_64_lib
tar xvf ../lua-5.3.5_Linux44_64_lib.tar
cd ..
luarocks LUA_LIBDIR=/home/samuel/lua-5.3.5_Linux44_64_lib/ install lua-webview --local --lua-version 5.3
eval `luarocks path --lua-version 5.3`
lua5.3 -e "require('webview').open('https://m.baidu.com/')"
```

The proposals I made may help to find out the link problem.
If you are able to compile and run webview without Lua then the issue is probably during the luarocks installation.

If you could share the commands to reproduce the luarocks package link problem then I will have a look.

Thank you,
Samuel

**Comment by futurepaycc** [comment]
I miss "LUA_LIBDIR=/home/samuel/lua-5.3.5_Linux44_64_lib/ " part in install command

now reinstall with:
sudo -E luarocks LUA_LIBDIR=/usr/lib install lua-webview  --lua-version 5.4

it works

so lua-webview  do't support 5.1 and luajit ?

**Comment by javalikescript** [comment]
lua-webview supports Lua 5.1 to 5.4
I never tried with luajit but I assume that luajit accepts standard Lua C modules, as noted [here](https://luajit.org/extensions.html).

**Comment by futurepaycc** [comment]
i have lua5.1~5.4 and luajit installed, only 5.4 works

**Comment by javalikescript** [comment]
Hello,
You are right, the latest lua-webview version is no more compatible with Lua 5.1, I will have a look.
Waiting for a fix you could use rock version [1.0-1](https://luarocks.org/modules/javalikescript/lua-webview/1.0-1) based on [1.0](https://github.com/javalikescript/lua-webview/releases/tag/1.0), as follow
```sh
luarocks LUA_LIBDIR=/home/samuel/lua-5.1.5_Linux35_64_lib/ install lua-webview 1.0-1 --local --lua-version 5.1
eval `luarocks path --lua-version 5.1`
lua5.1 -e "require('webview').open('https://m.baidu.com/')"
```

**Comment by javalikescript** [comment]
I restored the Lua 5.1 support, [here](https://github.com/javalikescript/lua-webview/commit/8009bd75cb0ddf6e873b5ae5e5a094e983e4103e), so the latest version should work fine again.

**Comment by futurepaycc** [comment]
ok,I'll try later
