### ISSUE TITLE
callback is broken

### ISSUE THREAD

**Issue by JonnyRodriguez** [javalikescript/lua-webview#4]
i build webview for lua 5.3 and 5.4 and the callback function is broke, if i run example/simple.lua when i click any button the page does nothing, it shows the page ok, but the callback is never called

**Comment by javalikescript** [comment]
Hello,
Sorry for the issue and the late reply.
Could you tell me what is your OS (Linux/Windows), the architecture (32/64/ARM) and the distribution/version?
Did you or could you try with the binaries (Lua+webview) available here: http://javalikescript.free.fr/lua/download.php ?
Could you build (see [readme](https://github.com/javalikescript/webview-c#example)) and try a C only example with a callback available here: [webview-example-2.c](https://github.com/javalikescript/webview-c/blob/master/webview-example-2.c) ?
Thank you in advance and have a good day,
Samuel

**Comment by javalikescript** [comment]
Additionally, I will need the detected browser. Just run the following command using you build:
`lua -e "require('webview').open('https://www.whatsmyua.info/')"`

**Comment by javalikescript** [comment]
Hello,
I fixed an issue in the browser callback registration under Linux/GTK, see https://github.com/javalikescript/webview-c/commit/db9d356a55b66aeef4737c0e285fe8f587c3e076
If you was using Linux/GTK then please check with the latest version.
Hope it helps and have a good day,
Samuel
