### ISSUE TITLE
LuaRocks install fail in ArchLinux

### ISSUE THREAD

**Issue by edubart** [javalikescript/lua-webview#5]
In ArchLinux after doing `luarocks install lua-webview` and trying to use the library, this error happens:

```
lua: error loading module 'webview' from file '/home/bart/.luarocks/lib/lua/5.4/webview.so':
	/home/bart/.luarocks/lib/lua/5.4/webview.so: undefined symbol: webkit_web_view_get_type
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	test.lua:1: in main chunk
	[C]: in ?
```

This happens because the invoked CC command to compile the library has the part `-L -lwebkit2gtk-4.0`, notice that there is directory after `-L` because `LUA_LIBDIR` is empty, so the GCC thinks `-lwebkit2gtk-4.0` is a library directory, and not a library to link.

# Workaround

Use `luarocks install LUA_LIBDIR=/usr/lib/lua/5.4 lua-webview --local` in ArchLinux. This will invoke CC with the correct command.

# How to fix

The `rock.mk` need patches for such situation, where `LUA_LIBDIR` is not defined by the user.

This is the same issue of https://github.com/javalikescript/lua-webview/issues/3

**Comment by javalikescript** [comment]
Hello,
Thank you for taking the time to report this problem and for the complete analysis.
I plan to update the makefile as suggested to protect against the unset variable, then I will be able to release a new rock.
Have a good day,
Samuel

**Comment by javalikescript** [comment]
See first part in commit a8dff995c0f380b93adef28bd96a5e1ec7caef17
