### ISSUE TITLE
Can't reuse webview

### ISSUE THREAD

**Issue by Nrosa01** [javalikescript/lua-webview#7]
I have a webview that I init with

```lua
local webviewLib = require('webview')
local webview = webviewLib.new('data:text/html,'..content, 'Example', 480, 240, false, false)
```

This snippet was based on examples/simple.lua

Now, I have a lua love application in which I create a thread to run the webview. Once the webview is terminated (by user clicking the close button in the windows), this can be retriggered with a button in my app. But, when I try to create the new webview again, it says it's nil in the loop function. 

```lua
webviewLib.callback(webview, function(value) end)

webviewLib.loop(webview)

while true do
    local command = love.thread.getChannel("webview_hook"):demand() -- Blocking function, wait for command from main thread

    if command == "show_editor" then -- if we are here, is because the previous loop was finished by the user, we need a new webview
        collectgarbage()
        print(webview) -- Should show nil, shows userdata
        webview = webviewLib.new('data:text/html,'..content, 'Example', 480, 240, false, false) -- it seems it returns nothing
        webviewLib.loop(webview) -- fail
    end
end
```

This is the console output

```
userdata: 0x0129fdfad420
Error: Thread error (Thread: 0x0129fa64a410)

libs/webview/simple.lua:33: bad argument #1 to 'loop' (webview expected, got nil)
stack traceback:
        [C]: in function 'loop'
        libs/webview/simple.lua:33: in main chunk
```

I've already look for information here: https://javalikescript.github.io/luajls/modules/jls.util.WebView.html#WebView:new

But there isn't anything that tells how to handle this. I could also just let the love thread finish and create it again when the users request de webview editor, but creating the thread is costly so I prefer to keep the thread alive.

Context (in case it helps):- I'm building a desktop falling sand sanbox simulation and I want to allow users to script particles like in https://studio.sandspiel.club. That page uses blockly from google, my app is a desktop app because this way I can get more performance via luajit ffi (yep, I'm running this with luajit), so I found about this webview plugin and I wanted to use it in my project, even if the webview window is not embedded in my game window.

To be clear, I also tested this in a simple lua project in a single thread and I still get the same issue, so I can assure that this is not related to love (which is just a C++ app that calls a few lua callabacks, but it's essentially luajit)

Edit: Oh right, I almost forgot, I'm on Windows, I use only webview.dll and webview2loader.dll. Luajls had 10mb of files which are heavier than my entire love project, so I just kept these two DLLs as it seems they are the only ones I know for a basic webview with callbacks that can be invoked via windows.external.invoke

**Comment by javalikescript** [comment]
Hello,

The webview usage is very restricted: one process, one thread, one webview.
I removed the restriction on multiple OLE initialization in commit 834f26d but, as said before, you enter in a trouble zone.
I will be pleased to assist you so do not hesitate if you still have any issue.

Have a good day,
Samuel

**Comment by Nrosa01** [comment]
I found out that calling webviewLib:clean(webview, true) works, but I have to bind the external methods again and so on, it's easier and almost as quick to boot to just create a new thread and dispose the old one. I will close the issue as this is solved now. Thank you so much for this lua extension, it helps a lot
