### ISSUE TITLE
Add build instructions for this specific module

### ISSUE THREAD

**Issue by Nrosa01** [javalikescript/lua-webview#8]
Hi, I'm interested in some specific parts of lua-webview that doesn't depend on luajls, I only use webview.dll, I don't even use WebView2Loader.dll. Now I did some modifications so I would like to compile this to a dll, but there isn't no makefile. I also tried to compile the whole luaclibs project following the instructions but failed.

Is there some way to compile only this module? I've tried compiling with both mingw and visual studio without success.

**Comment by javalikescript** [comment]
Hi,

Thank you for your interest, you could found makefile examples [here](https://github.com/javalikescript/lua-webview/blob/master/rock.mk) and [here](https://github.com/javalikescript/luaclibs/blob/master/lua-webview.mk).

I recommend to clone [luaclibs](https://github.com/javalikescript/luaclibs?tab=readme-ov-file#how-to-setup), follow the prerequisites then use the command `make lua-webview`. It will only build lua-webview and the required dependency here Lua.

You could also use directly the luarocks makefile by adapting the following command:
```sh
make -f rock.mk PLAT=windows MAKE=make CC=gcc LD=gcc LUA_LIBDIR=../luaclibs/lua/src LUA_INCDIR=../luaclibs/lua/src LUA=../luaclibs/lua/src/lua.exe
```

If you plan to use this module on Windows I also recommend to embed WebView2Loader as it is a very good alternative to IE 11 and broadly available on Windows 11.

Hope it helps and have a good day,
Samuel

**Comment by Nrosa01** [comment]
That worked! I don't know why I couldn't compile it before with msys mingw64, I'll look further into it but the importnat thing is that I can develop now. Thank you! ^^
